using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Mono.Cecil;
using Mono.Cecil.Cil;

using Tril.Attributes;
using Tril.Delegates;
using Tril.Models;

namespace Tril.Codoms
{
    /// <summary>
    /// Represents a finite check on a floating point number
    /// </summary>
    [Serializable]
    public sealed class CheckFloatingPointFinite : CheckFinite
    {
        /// <summary>
        /// Creates a new instance of Tril.Codoms.CheckFloatingPointFinite
        /// </summary>
        /// <param name="value"></param>
        public CheckFloatingPointFinite(ValueStatement value)
            : base(value)
        { }

        /// <summary>
        /// gets the C# representation of this code
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return ToString(null);
        }
        /// <summary>
        /// Returns the string representation of this code, as generated by the specified translator.
        /// </summary>
        /// <param name="translator"></param>
        /// <returns></returns>
        public override string ToString(CodomTranslator translator)
        {
            string trans = Codom.ToString(translator, this);
            if (trans != null)
                return trans;
            else
            {
                if (IsInline)
                    return "if (System.Double.IsNaN(" + Value.ToString(translator) + ") || System.Double.IsInfinity(" + Value.ToString(translator) + ")) throw new System.ArithmeticException()";
                return "if (System.Double.IsNaN(" + Value.ToString(translator) + ") || System.Double.IsInfinity(" + Value.ToString(translator) + ")) throw new System.ArithmeticException();";
            }
        }
    }
}
