using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Mono.Cecil;

using Tril.Attributes;
using Tril.Delegates;
using Tril.Models;

namespace Tril.Codoms
{
    /// <summary>
    /// Represents a piece of code supplied by the user
    /// </summary>
    [Serializable]
    public sealed class UserCode : Codom
    {
        string _cde;

        /// <summary>
        /// Creates a new instance of Tril.Codoms.UserCode
        /// </summary>
        /// <param name="code"></param>
        public UserCode(string code)
        {
            _cde = code == null ? "" : code;
        }

        /// <summary>
        /// Gets the user-defined code
        /// </summary>
        public string Code
        {
            get { return _cde; }
        }

        /// <summary>
        /// Returns the string representing this code
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return ToString(null);
        }
        /// <summary>
        /// Returns the string representation of this code, as generated by the specified translator.
        /// </summary>
        /// <param name="translator"></param>
        /// <returns></returns>
        public override string ToString(CodomTranslator translator)
        {
            string trans = Codom.ToString(translator, this);
            if (trans != null)
                return trans;
            else
            {
                return Code;
            }
        }
    }
}
